package view;

import controller.Controller;
import java.sql.ResultSet;


import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class MenuJframe extends JFrame {

    // ATRIBUTOS
    private Controller controller;
    // private JTable tablaLideres;
    private DefaultTableModel modeloLider;
    private DefaultTableModel modeloProyecto;
    private DefaultTableModel modeloCompra;

    public MenuJframe(Controller controller) {
        this.controller = controller;
        setTitle("Constructora UTP");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // setBounds(600, 200, 320, 300);
        construirTablaCompras();
        construirTablaLideres();
        construirTablaProyectos();
        initComponents();
        // this.tablaLideres.setModel(modelo);

        // Mostrar Jframe
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        // tablaProyectos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        // tablaCompras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Informe basado en los lideres");

        tablaLideres.setModel(modeloLider);
        /*
         * tablaLideres.setModel(new javax.swing.table.DefaultTableModel(
         * new Object [][] {
         * {null, null, null, null},
         * {null, null, null, null},
         * {null, null, null, null},
         * {null, null, null, null}
         * },
         * new String [] {
         * "Title 1", "Title 2", "Title 3", "Title 4"
         * }
         * ));
         */
        jScrollPane1.setViewportView(tablaLideres);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492,
                                                Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                                .addContainerGap()));

        jTabbedPane1.addTab("Lideres", jPanel1);

        jLabel2.setText("Informe basado en los proyectos cuya clasificación sea \"Casa Campestre\"");

        jLabel3.setText("y que están ubicados en Santa Marta, Cartagena y Barranquilla.");

        tablaProyectos.setModel(modeloProyecto);
        /*
         * tablaProyectos.setModel(new javax.swing.table.DefaultTableModel(
         * new Object[][] {
         * 
         * },
         * new String[] {
         * 
         * }));
         */
        jScrollPane2.setViewportView(tablaProyectos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(0, 106, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                .addContainerGap()));

        jTabbedPane1.addTab("Proyectos", jPanel2);

        jLabel4.setText("Informe basado en las compras realizadas al proveedor Homecenter");

        jLabel5.setText("para la ciudad de Salento.");

        tablaCompras.setModel(modeloCompra);
        /*
         * tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
         * new Object[][] {
         * 
         * },
         * new String[] {
         * 
         * }));
         */
        jScrollPane3.setViewportView(tablaCompras);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                                .addGap(0, 131, Short.MAX_VALUE))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                .addContainerGap()));

        jTabbedPane1.addTab("Compras", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(MenuJframe.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(MenuJframe.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(MenuJframe.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(MenuJframe.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>
    // //</editor-fold>
    //
    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new MenuJframe().setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTable tablaLideres;
    private javax.swing.JTable tablaProyectos;
    // End of variables declaration//GEN-END:variables

    public void construirTablaLideres() {
        Object columns[] = new Object[] { "ID", "Nombre", "Primer Apellido", "Segundo Apellido", "Ciudad Residencia" };
        TableModel m = new DefaultTableModel(
                new Object[][] {}, columns);
        // Crear tabla e indicar el modelo a la vista

        tablaLideres = new JTable(m);
        modeloLider = (DefaultTableModel) tablaLideres.getModel();
        JScrollPane scroll = new JScrollPane(tablaLideres);
        setVisible(true);
        mostrarDatosLideres();
        add(scroll);
    }

    public void mostrarDatosLideres() {
        ResultSet results = this.controller.getLider();
        try {
            while (results.next()) {
                int id = results.getInt("ID_Lider");
                String nombre = results.getString("Nombre");
                String primerApellido = results.getString("Primer_Apellido");
                String segundoApellido = results.getString("Segundo_Apellido");
                String ciudad = results.getString("Ciudad_Residencia");
                modeloLider.addRow(new Object[] { id, nombre, primerApellido, segundoApellido, ciudad });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void construirTablaProyectos() {
        Object columns[] = new Object[] { "ID Proyecto", "Constructora", "# Habitaciones", "Ciudad" };
        TableModel m = new DefaultTableModel(
                new Object[][] {}, columns);
        // Crear tabla e indicar el modelo a la vista

        tablaProyectos = new JTable(m);
        modeloProyecto = (DefaultTableModel) tablaProyectos.getModel();
        JScrollPane scroll = new JScrollPane(tablaProyectos);
        setVisible(true);
        mostrarDatosProyectos();
        add(scroll);
    }

    public void mostrarDatosProyectos() {
        ResultSet results = this.controller.getProyecto();
        try {
            while (results.next()) {
                int id = results.getInt("ID_Proyecto");
                String constructora = results.getString("Constructora");
                int numeroHabitaciones = results.getInt("Numero_Habitaciones");
                String ciudad = results.getString("Ciudad");
                modeloProyecto.addRow(new Object[] { id, constructora, numeroHabitaciones, ciudad });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void construirTablaCompras() {
        Object columns[] = new Object[] { "ID Compra", "Constructora", "Banco Vinculado" };
        TableModel m = new DefaultTableModel(
                new Object[][] {}, columns);
        // Crear tabla e indicar el modelo a la vista

        tablaCompras = new JTable(m);
        modeloCompra = (DefaultTableModel) tablaCompras.getModel();
        JScrollPane scroll = new JScrollPane(tablaCompras);
        setVisible(true);
        mostrarDatosCompras();
        add(scroll);
    }

    public void mostrarDatosCompras() {
        ResultSet results = this.controller.getCompra();
        try {
            while (results.next()) {
                int id = results.getInt("ID_Compra");
                String constructora = results.getString("Constructora");
                String banco = results.getString("Banco_Vinculado");
                modeloCompra.addRow(new Object[] { id, constructora, banco });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}


